language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script: ./scripts/travis_before_script.sh

env:
  - DB=mysql
  - DB=pgsql

script: phpunit --bootstrap ./tests/bootstrap.php ./tests/AllTests.php

branches:
  only:
    - master
    - master-1.2.x
